version: "3"
services:
  discord-bot:
    image: pi0neerpat/3box-discord-bo
    environment:
      - DISCORD_TOKEN=
      - INVOCATION_STRING=!verify
      - REDIS_URL=
      - REDIS_PASSWORD=
    ports:
      - "8080:8080"
